# YAML spec:
# https://aka.ms/yaml

name: Chocolatey Collection CI

variables:
  ChocoCIClient.labVMName: 'ChocoCIClient'
  ChocoCIClient.labVMFqdn: ''
  ChocoCIClient.labVMUserName: 'ansible'
# ChocoCIClient.labVMPassword: <secret>
  ChocoCIClient.ansibleUser: 'ansible-test'
# ChocoCIClient.ansiblePassword: <secret>

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

jobs:
- job: CreateVM
  displayName: 'Create Windows Client VM'
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: ms-azuredevtestlabs.tasks.azure-dtl-task-createvm.AzureDevTestLabsCreateVM@3
    name: AzureVM
    displayName: 'Create Windows Client VM'
    inputs:
      azureSubscription: 'Visual Studio Professional Subscription - Joel'
      LabId: '/subscriptions/6f2ac189-3b89-4d14-a0af-f5f808633f91/resourceGroups/choco-ci/providers/Microsoft.DevTestLab/labs/ChocoAnsibleLab'
      VirtualMachineName: '$(ChocoCIClient.labVMName)'
      TemplateFile: 'build/azure/client-template.json'
      ParameterOverrides: '-newVMName ''$(ChocoCIClient.labVMName)'' -userName ''$(ChocoCIClient.labVMUserName)'' -password ''$(ChocoCIClient.labVMPassword)'' -Configure_WinRM_hostName ''$(ChocoCIClient.labVMFqdn)'''

  - task: AzurePowerShell@4
    displayName: 'VM Setup'
    inputs:
      azureSubscription: 'Visual Studio Professional Subscription - Joel'
      ScriptPath: 'build/azure/Set-AzLabVMParams.ps1'
      ScriptArguments: '-LabVMId $(AzureVM.labVmId) -Username $(ChocoCIClient.ansibleUser) -Secret $(ChocoCIClient.ansiblePassword)'
      azurePowerShellVersion: LatestVersion

- job: Tests
  displayName: 'Chocolatey Collection Tests'
  dependsOn: CreateVM
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Bash@3
    displayName: 'Install Dependencies'
    inputs:
      targetType: filePath
      filePath: ./build/dependencies.sh

  - task: AzureCLI@2
    displayName: 'Run Ansible-Test for Collection'
    inputs:
      azureSubscription: 'Visual Studio Professional Subscription - Joel'
      scriptType: pscore
      scriptPath: 'build/Invoke-CollectionTests.ps1'
      arguments: '-IsCIBuild -Username $(ChocoCIClient.ansibleUser) -ComputerName $(ChocoCIClient.labVMFqdn) -Secret $(ChocoCIClient.ansiblePassword)'

  - task: PublishPipelineArtifact@1
    inputs:
      path: '$(System.DefaultWorkingDirectory)/testresults'
      artifact: 'Ansible-Test Output Files'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      searchFolder: '$(System.DefaultWorkingDirectory)/testresults'
      testResultsFiles: '*.xml'
      publishRunAttachments: true


- job: DestroyVM
  displayName: 'Destroy Azure Labs VM'
  pool:
    vmImage: ubuntu-latest
  dependsOn:
    - CreateVM
    - Tests
  condition: always()
  variables:
    labVmId: $[ dependencies.CreateVM.outputs['AzureVM.labVmId'] ]

  steps:
  - task: ms-azuredevtestlabs.tasks.azure-dtl-task-deleteVm.AzureDevTestLabsDeleteVM@3
    displayName: 'Destroy VM'
    inputs:
      azureSubscription: 'Visual Studio Professional Subscription - Joel'
      LabId: '/subscriptions/6f2ac189-3b89-4d14-a0af-f5f808633f91/resourceGroups/choco-ci/providers/Microsoft.DevTestLab/labs/ChocoAnsibleLab'
      LabVmId: '$(labVmId)'
    continueOnError: true
